-- Create "tenants" table
CREATE TABLE "public"."tenants" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "owner_id" bigint NOT NULL,
  "status" character varying NOT NULL DEFAULT 'PENDING',
  "expired_at" timestamptz NULL,
  "attributes" jsonb NOT NULL,
  "created_by" bigint NULL,
  "updated_by" bigint NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Set comment to column: "id" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."id" IS 'Primary Key ID';
-- Set comment to column: "name" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."name" IS 'Name of the tenant';
-- Set comment to column: "owner_id" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."owner_id" IS 'Owner user ID of the tenant';
-- Set comment to column: "status" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."status" IS 'Status of the tenant';
-- Set comment to column: "expired_at" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."expired_at" IS 'Expiration time of the tenant';
-- Set comment to column: "created_by" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."created_by" IS 'User who created this record';
-- Set comment to column: "updated_by" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."updated_by" IS 'User who last updated this record';
-- Set comment to column: "created_at" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."created_at" IS 'Creation timestamp of this record';
-- Set comment to column: "updated_at" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."updated_at" IS 'Last update timestamp of this record';
-- Set comment to column: "deleted_at" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."deleted_at" IS 'Timestamp when the record was deleted, if applicable';
-- Create "departments" table
CREATE TABLE "public"."departments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "parent_id" bigint NOT NULL,
  "name" character varying NOT NULL,
  "path" character varying NOT NULL,
  "attributes" jsonb NOT NULL,
  "created_by" bigint NULL,
  "updated_by" bigint NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "departments_tenants_departments" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Set comment to column: "parent_id" on table: "departments"
COMMENT ON COLUMN "public"."departments"."parent_id" IS 'Parent Department ID';
-- Set comment to column: "name" on table: "departments"
COMMENT ON COLUMN "public"."departments"."name" IS 'Name of the department';
-- Set comment to column: "created_by" on table: "departments"
COMMENT ON COLUMN "public"."departments"."created_by" IS 'User who created this record';
-- Set comment to column: "updated_by" on table: "departments"
COMMENT ON COLUMN "public"."departments"."updated_by" IS 'User who last updated this record';
-- Set comment to column: "created_at" on table: "departments"
COMMENT ON COLUMN "public"."departments"."created_at" IS 'Creation timestamp of this record';
-- Set comment to column: "updated_at" on table: "departments"
COMMENT ON COLUMN "public"."departments"."updated_at" IS 'Last update timestamp of this record';
-- Set comment to column: "deleted_at" on table: "departments"
COMMENT ON COLUMN "public"."departments"."deleted_at" IS 'Timestamp when the record was deleted, if applicable';
-- Set comment to column: "tenant_id" on table: "departments"
COMMENT ON COLUMN "public"."departments"."tenant_id" IS 'Tenant ID';
-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "email" character varying NOT NULL,
  "phone" character varying NOT NULL,
  "password" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'PENDING',
  "full_name" character varying NULL,
  "gender" character varying NOT NULL DEFAULT 'UNKNOWN',
  "avatar" character varying NULL,
  "language" character varying NOT NULL DEFAULT 'en',
  "timezone" character varying NOT NULL DEFAULT 'Asia/Shanghai',
  "created_by" bigint NULL,
  "updated_by" bigint NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create index "users_phone_key" to table: "users"
CREATE UNIQUE INDEX "users_phone_key" ON "public"."users" ("phone");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "public"."users" ("username");
-- Set comment to column: "id" on table: "users"
COMMENT ON COLUMN "public"."users"."id" IS 'Primary Key ID';
-- Set comment to column: "username" on table: "users"
COMMENT ON COLUMN "public"."users"."username" IS 'Username of the user';
-- Set comment to column: "email" on table: "users"
COMMENT ON COLUMN "public"."users"."email" IS 'Email address of the user';
-- Set comment to column: "phone" on table: "users"
COMMENT ON COLUMN "public"."users"."phone" IS 'Phone number of the user';
-- Set comment to column: "password" on table: "users"
COMMENT ON COLUMN "public"."users"."password" IS 'Password of the user';
-- Set comment to column: "status" on table: "users"
COMMENT ON COLUMN "public"."users"."status" IS 'Status of the user';
-- Set comment to column: "full_name" on table: "users"
COMMENT ON COLUMN "public"."users"."full_name" IS 'Full name of the user';
-- Set comment to column: "gender" on table: "users"
COMMENT ON COLUMN "public"."users"."gender" IS 'User gender';
-- Set comment to column: "avatar" on table: "users"
COMMENT ON COLUMN "public"."users"."avatar" IS 'Avatar URL of the user';
-- Set comment to column: "language" on table: "users"
COMMENT ON COLUMN "public"."users"."language" IS 'Preferred language of the user';
-- Set comment to column: "timezone" on table: "users"
COMMENT ON COLUMN "public"."users"."timezone" IS 'Preferred timezone of the user';
-- Set comment to column: "created_by" on table: "users"
COMMENT ON COLUMN "public"."users"."created_by" IS 'User who created this record';
-- Set comment to column: "updated_by" on table: "users"
COMMENT ON COLUMN "public"."users"."updated_by" IS 'User who last updated this record';
-- Set comment to column: "created_at" on table: "users"
COMMENT ON COLUMN "public"."users"."created_at" IS 'Creation timestamp of this record';
-- Set comment to column: "updated_at" on table: "users"
COMMENT ON COLUMN "public"."users"."updated_at" IS 'Last update timestamp of this record';
-- Set comment to column: "deleted_at" on table: "users"
COMMENT ON COLUMN "public"."users"."deleted_at" IS 'Timestamp when the record was deleted, if applicable';
-- Create "user_accounts" table
CREATE TABLE "public"."user_accounts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "platform" character varying NOT NULL,
  "identifier" character varying NOT NULL,
  "name" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_accounts_users_accounts" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "useraccount_platform_identifier" to table: "user_accounts"
CREATE UNIQUE INDEX "useraccount_platform_identifier" ON "public"."user_accounts" ("platform", "identifier");
-- Create index "useraccount_user_id" to table: "user_accounts"
CREATE INDEX "useraccount_user_id" ON "public"."user_accounts" ("user_id");
-- Set comment to column: "platform" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."platform" IS 'Social media platform (e.g., Twitter, Facebook)';
-- Set comment to column: "identifier" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."identifier" IS 'User''s account identifier on the platform';
-- Set comment to column: "name" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."name" IS 'User''s name on the platform';
-- Set comment to column: "created_at" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."created_at" IS 'Record creation timestamp';
-- Set comment to column: "updated_at" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."updated_at" IS 'Record last update timestamp';
-- Set comment to column: "deleted_at" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."deleted_at" IS 'Soft delete flag, null if not deleted';
-- Set comment to column: "user_id" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."user_id" IS 'Reference to SysUser ID';
-- Create "user_departments" table
CREATE TABLE "public"."user_departments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "attributes" jsonb NOT NULL,
  "dept_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_departments_departments_user_departments" FOREIGN KEY ("dept_id") REFERENCES "public"."departments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_departments_users_user_departments" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Set comment to column: "tenant_id" on table: "user_departments"
COMMENT ON COLUMN "public"."user_departments"."tenant_id" IS 'Tenant ID';
-- Set comment to column: "dept_id" on table: "user_departments"
COMMENT ON COLUMN "public"."user_departments"."dept_id" IS 'Department ID';
-- Set comment to column: "user_id" on table: "user_departments"
COMMENT ON COLUMN "public"."user_departments"."user_id" IS 'SysUser ID';
-- Create "user_tenants" table
CREATE TABLE "public"."user_tenants" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role_labels" jsonb NULL,
  "tenant_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_tenants_tenants_user_tenants" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_tenants_users_user_tenants" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Set comment to column: "tenant_id" on table: "user_tenants"
COMMENT ON COLUMN "public"."user_tenants"."tenant_id" IS 'Tenant ID';
-- Set comment to column: "user_id" on table: "user_tenants"
COMMENT ON COLUMN "public"."user_tenants"."user_id" IS 'SysUser ID';
