-- Create "tenants" table
CREATE TABLE "public"."tenants" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "owner_id" bigint NOT NULL,
  "type" character varying NOT NULL DEFAULT 'NORMAL',
  "path" public.ltree NULL,
  "level" integer NOT NULL DEFAULT 0,
  "status" character varying NOT NULL DEFAULT 'PENDING',
  "expired_at" timestamptz NULL,
  "attributes" jsonb NOT NULL,
  "created_by" bigint NULL,
  "updated_by" bigint NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "parent_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "tenants_tenants_children" FOREIGN KEY ("parent_id") REFERENCES "public"."tenants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "tenant_type_check" CHECK ((((type)::text = 'ROOT'::text) AND (parent_id IS NULL)) OR (((type)::text = ANY ((ARRAY['GROUP'::character varying, 'NORMAL'::character varying])::text[])) AND (parent_id = 100)) OR (((type)::text = 'SUB'::text) AND (parent_id IS NOT NULL)))
);
-- Create index "tenant_created_at" to table: "tenants"
CREATE INDEX "tenant_created_at" ON "public"."tenants" ("created_at");
-- Create index "tenant_expired_at" to table: "tenants"
CREATE INDEX "tenant_expired_at" ON "public"."tenants" ("expired_at");
-- Create index "tenant_level" to table: "tenants"
CREATE INDEX "tenant_level" ON "public"."tenants" ("level");
-- Create index "tenant_owner_id" to table: "tenants"
CREATE INDEX "tenant_owner_id" ON "public"."tenants" ("owner_id");
-- Create index "tenant_parent_id" to table: "tenants"
CREATE INDEX "tenant_parent_id" ON "public"."tenants" ("parent_id");
-- Create index "tenant_path" to table: "tenants"
CREATE INDEX "tenant_path" ON "public"."tenants" USING gist ("path");
-- Create index "tenant_status" to table: "tenants"
CREATE INDEX "tenant_status" ON "public"."tenants" ("status") WHERE (deleted_at IS NULL);
-- Create index "tenant_type" to table: "tenants"
CREATE INDEX "tenant_type" ON "public"."tenants" ("type");
-- Create index "tenant_type_parent_id" to table: "tenants"
CREATE INDEX "tenant_type_parent_id" ON "public"."tenants" ("type", "parent_id") WHERE (deleted_at IS NULL);
-- Set comment to column: "id" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."id" IS 'Primary Key ID';
-- Set comment to column: "name" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."name" IS 'Name of the tenant';
-- Set comment to column: "owner_id" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."owner_id" IS 'Owner user ID of the tenant';
-- Set comment to column: "type" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."type" IS 'Tenant type: ROOT(系统租户), NORMAL(普通租户), GROUP(集团型租户), SUB(子租户)';
-- Set comment to column: "path" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."path" IS 'Tenant hierarchy path using ltree';
-- Set comment to column: "level" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."level" IS 'Tenant hierarchy level (0 for root tenants)';
-- Set comment to column: "status" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."status" IS 'Status of the tenant';
-- Set comment to column: "expired_at" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."expired_at" IS 'Expiration time of the tenant';
-- Set comment to column: "attributes" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."attributes" IS 'Tenant attributes and metadata';
-- Set comment to column: "created_by" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."created_by" IS 'User who created this record';
-- Set comment to column: "updated_by" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."updated_by" IS 'User who last updated this record';
-- Set comment to column: "created_at" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."created_at" IS 'Creation timestamp of this record';
-- Set comment to column: "updated_at" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."updated_at" IS 'Last update timestamp of this record';
-- Set comment to column: "deleted_at" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."deleted_at" IS 'Timestamp when the record was deleted, if applicable';
-- Set comment to column: "parent_id" on table: "tenants"
COMMENT ON COLUMN "public"."tenants"."parent_id" IS 'Parent tenant ID for sub-tenants';
-- Create "departments" table
CREATE TABLE "public"."departments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "parent_id" bigint NOT NULL,
  "name" character varying NOT NULL,
  "path" public.ltree NOT NULL,
  "attributes" jsonb NOT NULL,
  "created_by" bigint NULL,
  "updated_by" bigint NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "departments_tenants_departments" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "department_created_at" to table: "departments"
CREATE INDEX "department_created_at" ON "public"."departments" ("created_at");
-- Create index "department_path" to table: "departments"
CREATE INDEX "department_path" ON "public"."departments" USING gist ("path");
-- Create index "department_tenant_id" to table: "departments"
CREATE INDEX "department_tenant_id" ON "public"."departments" ("tenant_id");
-- Create index "department_tenant_id_parent_id" to table: "departments"
CREATE INDEX "department_tenant_id_parent_id" ON "public"."departments" ("tenant_id", "parent_id") WHERE (deleted_at IS NULL);
-- Set comment to column: "id" on table: "departments"
COMMENT ON COLUMN "public"."departments"."id" IS 'Primary Key ID';
-- Set comment to column: "parent_id" on table: "departments"
COMMENT ON COLUMN "public"."departments"."parent_id" IS 'Parent Department ID';
-- Set comment to column: "name" on table: "departments"
COMMENT ON COLUMN "public"."departments"."name" IS 'Name of the department';
-- Set comment to column: "path" on table: "departments"
COMMENT ON COLUMN "public"."departments"."path" IS 'save ltree path';
-- Set comment to column: "created_by" on table: "departments"
COMMENT ON COLUMN "public"."departments"."created_by" IS 'User who created this record';
-- Set comment to column: "updated_by" on table: "departments"
COMMENT ON COLUMN "public"."departments"."updated_by" IS 'User who last updated this record';
-- Set comment to column: "created_at" on table: "departments"
COMMENT ON COLUMN "public"."departments"."created_at" IS 'Creation timestamp of this record';
-- Set comment to column: "updated_at" on table: "departments"
COMMENT ON COLUMN "public"."departments"."updated_at" IS 'Last update timestamp of this record';
-- Set comment to column: "deleted_at" on table: "departments"
COMMENT ON COLUMN "public"."departments"."deleted_at" IS 'Timestamp when the record was deleted, if applicable';
-- Set comment to column: "tenant_id" on table: "departments"
COMMENT ON COLUMN "public"."departments"."tenant_id" IS 'Tenant ID';
-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "email" character varying NULL,
  "phone" character varying NULL,
  "password" character varying NULL,
  "status" character varying NOT NULL DEFAULT 'PENDING',
  "full_name" character varying NULL,
  "gender" character varying NOT NULL DEFAULT 'UNKNOWN',
  "avatar" character varying NULL,
  "language" character varying NOT NULL DEFAULT 'en',
  "timezone" character varying NOT NULL DEFAULT 'Asia/Shanghai',
  "created_by" bigint NULL,
  "updated_by" bigint NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_contact_or_password_check" CHECK ((email IS NOT NULL) OR (phone IS NOT NULL) OR (password IS NOT NULL))
);
-- Create index "user_status_updated_at" to table: "users"
CREATE INDEX "user_status_updated_at" ON "public"."users" ("status", "updated_at");
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create index "users_phone_key" to table: "users"
CREATE UNIQUE INDEX "users_phone_key" ON "public"."users" ("phone");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "public"."users" ("username");
-- Set comment to column: "id" on table: "users"
COMMENT ON COLUMN "public"."users"."id" IS 'Primary Key ID';
-- Set comment to column: "username" on table: "users"
COMMENT ON COLUMN "public"."users"."username" IS 'Username of the user';
-- Set comment to column: "email" on table: "users"
COMMENT ON COLUMN "public"."users"."email" IS 'Email address of the user';
-- Set comment to column: "phone" on table: "users"
COMMENT ON COLUMN "public"."users"."phone" IS 'Phone number of the user';
-- Set comment to column: "password" on table: "users"
COMMENT ON COLUMN "public"."users"."password" IS 'Password of the user';
-- Set comment to column: "status" on table: "users"
COMMENT ON COLUMN "public"."users"."status" IS 'Status of the user';
-- Set comment to column: "full_name" on table: "users"
COMMENT ON COLUMN "public"."users"."full_name" IS 'Full name of the user';
-- Set comment to column: "gender" on table: "users"
COMMENT ON COLUMN "public"."users"."gender" IS 'User gender';
-- Set comment to column: "avatar" on table: "users"
COMMENT ON COLUMN "public"."users"."avatar" IS 'Avatar URL of the user';
-- Set comment to column: "language" on table: "users"
COMMENT ON COLUMN "public"."users"."language" IS 'Preferred language of the user';
-- Set comment to column: "timezone" on table: "users"
COMMENT ON COLUMN "public"."users"."timezone" IS 'Preferred timezone of the user';
-- Set comment to column: "created_by" on table: "users"
COMMENT ON COLUMN "public"."users"."created_by" IS 'User who created this record';
-- Set comment to column: "updated_by" on table: "users"
COMMENT ON COLUMN "public"."users"."updated_by" IS 'User who last updated this record';
-- Set comment to column: "created_at" on table: "users"
COMMENT ON COLUMN "public"."users"."created_at" IS 'Creation timestamp of this record';
-- Set comment to column: "updated_at" on table: "users"
COMMENT ON COLUMN "public"."users"."updated_at" IS 'Last update timestamp of this record';
-- Set comment to column: "deleted_at" on table: "users"
COMMENT ON COLUMN "public"."users"."deleted_at" IS 'Timestamp when the record was deleted, if applicable';
-- Create "user_accounts" table
CREATE TABLE "public"."user_accounts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "platform" character varying NOT NULL,
  "identifier" character varying NOT NULL,
  "name" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_accounts_users_accounts" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "useraccount_platform_identifier" to table: "user_accounts"
CREATE UNIQUE INDEX "useraccount_platform_identifier" ON "public"."user_accounts" ("platform", "identifier");
-- Create index "useraccount_user_id" to table: "user_accounts"
CREATE INDEX "useraccount_user_id" ON "public"."user_accounts" ("user_id");
-- Set comment to column: "platform" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."platform" IS 'Social media platform (e.g., Twitter, Facebook)';
-- Set comment to column: "identifier" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."identifier" IS 'User''s account identifier on the platform';
-- Set comment to column: "name" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."name" IS 'User''s name on the platform';
-- Set comment to column: "created_at" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."created_at" IS 'Record creation timestamp';
-- Set comment to column: "updated_at" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."updated_at" IS 'Record last update timestamp';
-- Set comment to column: "deleted_at" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."deleted_at" IS 'Soft delete flag, null if not deleted';
-- Set comment to column: "user_id" on table: "user_accounts"
COMMENT ON COLUMN "public"."user_accounts"."user_id" IS 'Reference to SysUser ID';
-- Create "user_departments" table
CREATE TABLE "public"."user_departments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" bigint NOT NULL,
  "attributes" jsonb NOT NULL,
  "dept_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_departments_departments_user_departments" FOREIGN KEY ("dept_id") REFERENCES "public"."departments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_departments_users_user_departments" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "userdepartment_dept_id" to table: "user_departments"
CREATE INDEX "userdepartment_dept_id" ON "public"."user_departments" ("dept_id");
-- Create index "userdepartment_tenant_id" to table: "user_departments"
CREATE INDEX "userdepartment_tenant_id" ON "public"."user_departments" ("tenant_id");
-- Create index "userdepartment_user_id" to table: "user_departments"
CREATE INDEX "userdepartment_user_id" ON "public"."user_departments" ("user_id");
-- Create index "userdepartment_user_id_dept_id" to table: "user_departments"
CREATE UNIQUE INDEX "userdepartment_user_id_dept_id" ON "public"."user_departments" ("user_id", "dept_id");
-- Set comment to column: "tenant_id" on table: "user_departments"
COMMENT ON COLUMN "public"."user_departments"."tenant_id" IS 'Tenant ID';
-- Set comment to column: "dept_id" on table: "user_departments"
COMMENT ON COLUMN "public"."user_departments"."dept_id" IS 'Department ID';
-- Set comment to column: "user_id" on table: "user_departments"
COMMENT ON COLUMN "public"."user_departments"."user_id" IS 'SysUser ID';
-- Create "user_tenants" table
CREATE TABLE "public"."user_tenants" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role_labels" jsonb NULL,
  "tenant_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_tenants_tenants_user_tenants" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_tenants_users_user_tenants" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "usertenant_tenant_id" to table: "user_tenants"
CREATE INDEX "usertenant_tenant_id" ON "public"."user_tenants" ("tenant_id");
-- Create index "usertenant_user_id" to table: "user_tenants"
CREATE INDEX "usertenant_user_id" ON "public"."user_tenants" ("user_id");
-- Create index "usertenant_user_id_tenant_id" to table: "user_tenants"
CREATE UNIQUE INDEX "usertenant_user_id_tenant_id" ON "public"."user_tenants" ("user_id", "tenant_id");
-- Set comment to column: "tenant_id" on table: "user_tenants"
COMMENT ON COLUMN "public"."user_tenants"."tenant_id" IS 'Tenant ID';
-- Set comment to column: "user_id" on table: "user_tenants"
COMMENT ON COLUMN "public"."user_tenants"."user_id" IS 'SysUser ID';
