// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--rc1
// source: user_management/v1/department.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Pid           string                 `protobuf:"bytes,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_user_management_v1_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{0}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Department) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *Department) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Department) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Department) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Department) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Department) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Pid           string                 `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentRequest) Reset() {
	*x = CreateDepartmentRequest{}
	mi := &file_user_management_v1_department_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentRequest) ProtoMessage() {}

func (x *CreateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDepartmentRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateDepartmentRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *CreateDepartmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Department    *Department            `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentResponse) Reset() {
	*x = CreateDepartmentResponse{}
	mi := &file_user_management_v1_department_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentResponse) ProtoMessage() {}

func (x *CreateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*CreateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDepartmentResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *CreateDepartmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateDepartmentResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *CreateDepartmentResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentRequest) Reset() {
	*x = DeleteDepartmentRequest{}
	mi := &file_user_management_v1_department_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentRequest) ProtoMessage() {}

func (x *DeleteDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentResponse) Reset() {
	*x = DeleteDepartmentResponse{}
	mi := &file_user_management_v1_department_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentResponse) ProtoMessage() {}

func (x *DeleteDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDepartmentResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *DeleteDepartmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteDepartmentResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Pid           string                 `protobuf:"bytes,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentRequest) Reset() {
	*x = UpdateDepartmentRequest{}
	mi := &file_user_management_v1_department_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentRequest) ProtoMessage() {}

func (x *UpdateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Department    *Department            `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentResponse) Reset() {
	*x = UpdateDepartmentResponse{}
	mi := &file_user_management_v1_department_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentResponse) ProtoMessage() {}

func (x *UpdateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDepartmentResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *UpdateDepartmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateDepartmentResponse) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *UpdateDepartmentResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentRequest) Reset() {
	*x = GetDepartmentRequest{}
	mi := &file_user_management_v1_department_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentRequest) ProtoMessage() {}

func (x *GetDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	IsDesc        bool                   `protobuf:"varint,4,opt,name=is_desc,json=isDesc,proto3" json:"is_desc,omitempty"`
	Pid           string                 `protobuf:"bytes,5,opt,name=pid,proto3" json:"pid,omitempty"` // 筛选特定父部门下的子部门
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsRequest) Reset() {
	*x = ListDepartmentsRequest{}
	mi := &file_user_management_v1_department_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsRequest) ProtoMessage() {}

func (x *ListDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{8}
}

func (x *ListDepartmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDepartmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDepartmentsRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ListDepartmentsRequest) GetIsDesc() bool {
	if x != nil {
		return x.IsDesc
	}
	return false
}

func (x *ListDepartmentsRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ListDepartmentsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDepartmentsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListDepartmentsResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Result        bool                                `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Code          int32                               `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          *ListDepartmentsResponse_PageResult `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Msg           string                              `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsResponse) Reset() {
	*x = ListDepartmentsResponse{}
	mi := &file_user_management_v1_department_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsResponse) ProtoMessage() {}

func (x *ListDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*ListDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{9}
}

func (x *ListDepartmentsResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *ListDepartmentsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListDepartmentsResponse) GetData() *ListDepartmentsResponse_PageResult {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListDepartmentsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AddUsersToDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersToDepartmentRequest) Reset() {
	*x = AddUsersToDepartmentRequest{}
	mi := &file_user_management_v1_department_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersToDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersToDepartmentRequest) ProtoMessage() {}

func (x *AddUsersToDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersToDepartmentRequest.ProtoReflect.Descriptor instead.
func (*AddUsersToDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{10}
}

func (x *AddUsersToDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *AddUsersToDepartmentRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RemoveUsersFromDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUsersFromDepartmentRequest) Reset() {
	*x = RemoveUsersFromDepartmentRequest{}
	mi := &file_user_management_v1_department_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUsersFromDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUsersFromDepartmentRequest) ProtoMessage() {}

func (x *RemoveUsersFromDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUsersFromDepartmentRequest.ProtoReflect.Descriptor instead.
func (*RemoveUsersFromDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveUsersFromDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *RemoveUsersFromDepartmentRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ListDepartmentUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentUsersRequest) Reset() {
	*x = ListDepartmentUsersRequest{}
	mi := &file_user_management_v1_department_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentUsersRequest) ProtoMessage() {}

func (x *ListDepartmentUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentUsersRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{12}
}

func (x *ListDepartmentUsersRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *ListDepartmentUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDepartmentUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDepartmentsResponse_PageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Departments   []*Department          `protobuf:"bytes,2,rep,name=departments,proto3" json:"departments,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsResponse_PageResult) Reset() {
	*x = ListDepartmentsResponse_PageResult{}
	mi := &file_user_management_v1_department_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsResponse_PageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsResponse_PageResult) ProtoMessage() {}

func (x *ListDepartmentsResponse_PageResult) ProtoReflect() protoreflect.Message {
	mi := &file_user_management_v1_department_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsResponse_PageResult.ProtoReflect.Descriptor instead.
func (*ListDepartmentsResponse_PageResult) Descriptor() ([]byte, []int) {
	return file_user_management_v1_department_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ListDepartmentsResponse_PageResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDepartmentsResponse_PageResult) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

func (x *ListDepartmentsResponse_PageResult) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDepartmentsResponse_PageResult) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_user_management_v1_department_proto protoreflect.FileDescriptor

const file_user_management_v1_department_proto_rawDesc = "" +
	"\n" +
	"#user_management/v1/department.proto\x12\x12user_management.v1\x1a\x1cgoogle/api/annotations.proto\"\xf4\x01\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\tR\x03pid\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"u\n" +
	"\x17CreateDepartmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\tR\x03pid\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x98\x01\n" +
	"\x18CreateDepartmentResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12>\n" +
	"\n" +
	"department\x18\x03 \x01(\v2\x1e.user_management.v1.DepartmentR\n" +
	"department\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\")\n" +
	"\x17DeleteDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x18DeleteDepartmentResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\x85\x01\n" +
	"\x17UpdateDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\tR\x03pid\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\x98\x01\n" +
	"\x18UpdateDepartmentResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12>\n" +
	"\n" +
	"department\x18\x03 \x01(\v2\x1e.user_management.v1.DepartmentR\n" +
	"department\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\"&\n" +
	"\x14GetDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb2\x01\n" +
	"\x16ListDepartmentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\x12\x17\n" +
	"\ais_desc\x18\x04 \x01(\bR\x06isDesc\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\tR\x03pid\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\"\xbb\x02\n" +
	"\x17ListDepartmentsResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12J\n" +
	"\x04data\x18\x03 \x01(\v26.user_management.v1.ListDepartmentsResponse.PageResultR\x04data\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x1a\x95\x01\n" +
	"\n" +
	"PageResult\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12@\n" +
	"\vdepartments\x18\x02 \x03(\v2\x1e.user_management.v1.DepartmentR\vdepartments\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"]\n" +
	"\x1bAddUsersToDepartmentRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"b\n" +
	" RemoveUsersFromDepartmentRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"r\n" +
	"\x1aListDepartmentUsersRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize2\xc4\x04\n" +
	"\x11DepartmentService\x12\x89\x01\n" +
	"\x10CreateDepartment\x12+.user_management.v1.CreateDepartmentRequest\x1a,.user_management.v1.CreateDepartmentResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/departments\x12\x8b\x01\n" +
	"\x10DeleteDepartment\x12+.user_management.v1.DeleteDepartmentRequest\x1a,.user_management.v1.DeleteDepartmentResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/departments/{id}\x12\x8e\x01\n" +
	"\x10UpdateDepartment\x12+.user_management.v1.UpdateDepartmentRequest\x1a,.user_management.v1.UpdateDepartmentResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/v1/departments/{id}\x12\x83\x01\n" +
	"\x0fListDepartments\x12*.user_management.v1.ListDepartmentsRequest\x1a+.user_management.v1.ListDepartmentsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/departmentsB5Z3github.com/yc-alpha/admin/api/user_management/v1;v1b\x06proto3"

var (
	file_user_management_v1_department_proto_rawDescOnce sync.Once
	file_user_management_v1_department_proto_rawDescData []byte
)

func file_user_management_v1_department_proto_rawDescGZIP() []byte {
	file_user_management_v1_department_proto_rawDescOnce.Do(func() {
		file_user_management_v1_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_management_v1_department_proto_rawDesc), len(file_user_management_v1_department_proto_rawDesc)))
	})
	return file_user_management_v1_department_proto_rawDescData
}

var file_user_management_v1_department_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_management_v1_department_proto_goTypes = []any{
	(*Department)(nil),                         // 0: user_management.v1.Department
	(*CreateDepartmentRequest)(nil),            // 1: user_management.v1.CreateDepartmentRequest
	(*CreateDepartmentResponse)(nil),           // 2: user_management.v1.CreateDepartmentResponse
	(*DeleteDepartmentRequest)(nil),            // 3: user_management.v1.DeleteDepartmentRequest
	(*DeleteDepartmentResponse)(nil),           // 4: user_management.v1.DeleteDepartmentResponse
	(*UpdateDepartmentRequest)(nil),            // 5: user_management.v1.UpdateDepartmentRequest
	(*UpdateDepartmentResponse)(nil),           // 6: user_management.v1.UpdateDepartmentResponse
	(*GetDepartmentRequest)(nil),               // 7: user_management.v1.GetDepartmentRequest
	(*ListDepartmentsRequest)(nil),             // 8: user_management.v1.ListDepartmentsRequest
	(*ListDepartmentsResponse)(nil),            // 9: user_management.v1.ListDepartmentsResponse
	(*AddUsersToDepartmentRequest)(nil),        // 10: user_management.v1.AddUsersToDepartmentRequest
	(*RemoveUsersFromDepartmentRequest)(nil),   // 11: user_management.v1.RemoveUsersFromDepartmentRequest
	(*ListDepartmentUsersRequest)(nil),         // 12: user_management.v1.ListDepartmentUsersRequest
	(*ListDepartmentsResponse_PageResult)(nil), // 13: user_management.v1.ListDepartmentsResponse.PageResult
}
var file_user_management_v1_department_proto_depIdxs = []int32{
	0,  // 0: user_management.v1.CreateDepartmentResponse.department:type_name -> user_management.v1.Department
	0,  // 1: user_management.v1.UpdateDepartmentResponse.department:type_name -> user_management.v1.Department
	13, // 2: user_management.v1.ListDepartmentsResponse.data:type_name -> user_management.v1.ListDepartmentsResponse.PageResult
	0,  // 3: user_management.v1.ListDepartmentsResponse.PageResult.departments:type_name -> user_management.v1.Department
	1,  // 4: user_management.v1.DepartmentService.CreateDepartment:input_type -> user_management.v1.CreateDepartmentRequest
	3,  // 5: user_management.v1.DepartmentService.DeleteDepartment:input_type -> user_management.v1.DeleteDepartmentRequest
	5,  // 6: user_management.v1.DepartmentService.UpdateDepartment:input_type -> user_management.v1.UpdateDepartmentRequest
	8,  // 7: user_management.v1.DepartmentService.ListDepartments:input_type -> user_management.v1.ListDepartmentsRequest
	2,  // 8: user_management.v1.DepartmentService.CreateDepartment:output_type -> user_management.v1.CreateDepartmentResponse
	4,  // 9: user_management.v1.DepartmentService.DeleteDepartment:output_type -> user_management.v1.DeleteDepartmentResponse
	6,  // 10: user_management.v1.DepartmentService.UpdateDepartment:output_type -> user_management.v1.UpdateDepartmentResponse
	9,  // 11: user_management.v1.DepartmentService.ListDepartments:output_type -> user_management.v1.ListDepartmentsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_management_v1_department_proto_init() }
func file_user_management_v1_department_proto_init() {
	if File_user_management_v1_department_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_management_v1_department_proto_rawDesc), len(file_user_management_v1_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_management_v1_department_proto_goTypes,
		DependencyIndexes: file_user_management_v1_department_proto_depIdxs,
		MessageInfos:      file_user_management_v1_department_proto_msgTypes,
	}.Build()
	File_user_management_v1_department_proto = out.File
	file_user_management_v1_department_proto_goTypes = nil
	file_user_management_v1_department_proto_depIdxs = nil
}
