// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--rc1
// source: admin/v1/sys_menu.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 菜单基础信息
type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                     // 菜单ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                 // 菜单名称
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                               // 显示名称
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`         // 父菜单ID
	OrderNum      int32                  `protobuf:"varint,5,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`        // 显示顺序
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`                                 // 路由地址
	Component     string                 `protobuf:"bytes,7,opt,name=component,proto3" json:"component,omitempty"`                       // 组件路径
	Redirect      string                 `protobuf:"bytes,8,opt,name=redirect,proto3" json:"redirect,omitempty"`                         // 跳转地址
	Icon          string                 `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`                                 // 菜单图标
	IsHidden      bool                   `protobuf:"varint,10,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`       // 是否隐藏
	IsDisabled    bool                   `protobuf:"varint,11,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"` // 是否禁用
	IsExternal    bool                   `protobuf:"varint,12,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"` // 是否外链
	Permission    string                 `protobuf:"bytes,13,opt,name=permission,proto3" json:"permission,omitempty"`                    // 权限标识
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`     // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`     // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Menu) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Menu) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Menu) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *Menu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Menu) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Menu) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *Menu) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *Menu) GetIsExternal() bool {
	if x != nil {
		return x.IsExternal
	}
	return false
}

func (x *Menu) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *Menu) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Menu) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 获取菜单列表请求
type ListMenuRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Keyword         string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                                         // 搜索关键字
	IncludeDisabled bool                   `protobuf:"varint,2,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"` // 是否包含禁用菜单
	IncludeHidden   bool                   `protobuf:"varint,3,opt,name=include_hidden,json=includeHidden,proto3" json:"include_hidden,omitempty"`       // 是否包含隐藏菜单
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMenuRequest) Reset() {
	*x = ListMenuRequest{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuRequest) ProtoMessage() {}

func (x *ListMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuRequest.ProtoReflect.Descriptor instead.
func (*ListMenuRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{1}
}

func (x *ListMenuRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListMenuRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

func (x *ListMenuRequest) GetIncludeHidden() bool {
	if x != nil {
		return x.IncludeHidden
	}
	return false
}

// 获取菜单列表响应
type ListMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Menu                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`  // 菜单列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuResponse) Reset() {
	*x = ListMenuResponse{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuResponse) ProtoMessage() {}

func (x *ListMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuResponse.ProtoReflect.Descriptor instead.
func (*ListMenuResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{2}
}

func (x *ListMenuResponse) GetItems() []*Menu {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMenuResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取菜单详情请求
type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 菜单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{3}
}

func (x *GetMenuRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取菜单详情响应
type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *Menu                  `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"` // 菜单信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{4}
}

func (x *GetMenuResponse) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

// 创建菜单请求
type CreateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                 // 菜单名称
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                               // 显示名称
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`         // 父菜单ID
	OrderNum      int32                  `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`        // 显示顺序
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`                                 // 路由地址
	Component     string                 `protobuf:"bytes,6,opt,name=component,proto3" json:"component,omitempty"`                       // 组件路径
	Redirect      string                 `protobuf:"bytes,7,opt,name=redirect,proto3" json:"redirect,omitempty"`                         // 跳转地址
	Icon          string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`                                 // 菜单图标
	IsHidden      bool                   `protobuf:"varint,9,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`        // 是否隐藏
	IsDisabled    bool                   `protobuf:"varint,10,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"` // 是否禁用
	IsExternal    bool                   `protobuf:"varint,11,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"` // 是否外链
	Permission    string                 `protobuf:"bytes,12,opt,name=permission,proto3" json:"permission,omitempty"`                    // 权限标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuRequest) Reset() {
	*x = CreateMenuRequest{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuRequest) ProtoMessage() {}

func (x *CreateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMenuRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateMenuRequest) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *CreateMenuRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateMenuRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *CreateMenuRequest) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *CreateMenuRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateMenuRequest) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *CreateMenuRequest) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *CreateMenuRequest) GetIsExternal() bool {
	if x != nil {
		return x.IsExternal
	}
	return false
}

func (x *CreateMenuRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

// 创建菜单响应
type CreateMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 新创建的菜单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuResponse) Reset() {
	*x = CreateMenuResponse{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuResponse) ProtoMessage() {}

func (x *CreateMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuResponse.ProtoReflect.Descriptor instead.
func (*CreateMenuResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMenuResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 更新菜单请求
type UpdateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                     // 菜单ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                 // 菜单名称
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                               // 显示名称
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`         // 父菜单ID
	OrderNum      int32                  `protobuf:"varint,5,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`        // 显示顺序
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`                                 // 路由地址
	Component     string                 `protobuf:"bytes,7,opt,name=component,proto3" json:"component,omitempty"`                       // 组件路径
	Redirect      string                 `protobuf:"bytes,8,opt,name=redirect,proto3" json:"redirect,omitempty"`                         // 跳转地址
	Icon          string                 `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`                                 // 菜单图标
	IsHidden      bool                   `protobuf:"varint,10,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`       // 是否隐藏
	IsDisabled    bool                   `protobuf:"varint,11,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"` // 是否禁用
	IsExternal    bool                   `protobuf:"varint,12,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"` // 是否外链
	Permission    string                 `protobuf:"bytes,13,opt,name=permission,proto3" json:"permission,omitempty"`                    // 权限标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuRequest) Reset() {
	*x = UpdateMenuRequest{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuRequest) ProtoMessage() {}

func (x *UpdateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMenuRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMenuRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UpdateMenuRequest) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *UpdateMenuRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateMenuRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *UpdateMenuRequest) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *UpdateMenuRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateMenuRequest) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *UpdateMenuRequest) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *UpdateMenuRequest) GetIsExternal() bool {
	if x != nil {
		return x.IsExternal
	}
	return false
}

func (x *UpdateMenuRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

// 更新菜单响应
type UpdateMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 更新是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuResponse) Reset() {
	*x = UpdateMenuResponse{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuResponse) ProtoMessage() {}

func (x *UpdateMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuResponse.ProtoReflect.Descriptor instead.
func (*UpdateMenuResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMenuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除菜单请求
type DeleteMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 菜单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuRequest) Reset() {
	*x = DeleteMenuRequest{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuRequest) ProtoMessage() {}

func (x *DeleteMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMenuRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 删除菜单响应
type DeleteMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 删除是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuResponse) Reset() {
	*x = DeleteMenuResponse{}
	mi := &file_admin_v1_sys_menu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuResponse) ProtoMessage() {}

func (x *DeleteMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_sys_menu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuResponse.ProtoReflect.Descriptor instead.
func (*DeleteMenuResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_sys_menu_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMenuResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_admin_v1_sys_menu_proto protoreflect.FileDescriptor

const file_admin_v1_sys_menu_proto_rawDesc = "" +
	"\n" +
	"\x17admin/v1/sys_menu.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\"\x99\x03\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x1b\n" +
	"\torder_num\x18\x05 \x01(\x05R\borderNum\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\a \x01(\tR\tcomponent\x12\x1a\n" +
	"\bredirect\x18\b \x01(\tR\bredirect\x12\x12\n" +
	"\x04icon\x18\t \x01(\tR\x04icon\x12\x1b\n" +
	"\tis_hidden\x18\n" +
	" \x01(\bR\bisHidden\x12\x1f\n" +
	"\vis_disabled\x18\v \x01(\bR\n" +
	"isDisabled\x12\x1f\n" +
	"\vis_external\x18\f \x01(\bR\n" +
	"isExternal\x12\x1e\n" +
	"\n" +
	"permission\x18\r \x01(\tR\n" +
	"permission\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"}\n" +
	"\x0fListMenuRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12)\n" +
	"\x10include_disabled\x18\x02 \x01(\bR\x0fincludeDisabled\x12%\n" +
	"\x0einclude_hidden\x18\x03 \x01(\bR\rincludeHidden\"N\n" +
	"\x10ListMenuResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.admin.v1.MenuR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\" \n" +
	"\x0eGetMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fGetMenuResponse\x12\"\n" +
	"\x04menu\x18\x01 \x01(\v2\x0e.admin.v1.MenuR\x04menu\"\xd8\x02\n" +
	"\x11CreateMenuRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x1b\n" +
	"\torder_num\x18\x04 \x01(\x05R\borderNum\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\x06 \x01(\tR\tcomponent\x12\x1a\n" +
	"\bredirect\x18\a \x01(\tR\bredirect\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x1b\n" +
	"\tis_hidden\x18\t \x01(\bR\bisHidden\x12\x1f\n" +
	"\vis_disabled\x18\n" +
	" \x01(\bR\n" +
	"isDisabled\x12\x1f\n" +
	"\vis_external\x18\v \x01(\bR\n" +
	"isExternal\x12\x1e\n" +
	"\n" +
	"permission\x18\f \x01(\tR\n" +
	"permission\"$\n" +
	"\x12CreateMenuResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe8\x02\n" +
	"\x11UpdateMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x1b\n" +
	"\torder_num\x18\x05 \x01(\x05R\borderNum\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\a \x01(\tR\tcomponent\x12\x1a\n" +
	"\bredirect\x18\b \x01(\tR\bredirect\x12\x12\n" +
	"\x04icon\x18\t \x01(\tR\x04icon\x12\x1b\n" +
	"\tis_hidden\x18\n" +
	" \x01(\bR\bisHidden\x12\x1f\n" +
	"\vis_disabled\x18\v \x01(\bR\n" +
	"isDisabled\x12\x1f\n" +
	"\vis_external\x18\f \x01(\bR\n" +
	"isExternal\x12\x1e\n" +
	"\n" +
	"permission\x18\r \x01(\tR\n" +
	"permission\".\n" +
	"\x12UpdateMenuResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11DeleteMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteMenuResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe2\x03\n" +
	"\x0eSysMenuService\x12T\n" +
	"\bListMenu\x12\x19.admin.v1.ListMenuRequest\x1a\x1a.admin.v1.ListMenuResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/menus\x12V\n" +
	"\aGetMenu\x12\x18.admin.v1.GetMenuRequest\x1a\x19.admin.v1.GetMenuResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/menus/{id}\x12]\n" +
	"\n" +
	"CreateMenu\x12\x1b.admin.v1.CreateMenuRequest\x1a\x1c.admin.v1.CreateMenuResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/menus\x12b\n" +
	"\n" +
	"UpdateMenu\x12\x1b.admin.v1.UpdateMenuRequest\x1a\x1c.admin.v1.UpdateMenuResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/menus/{id}\x12_\n" +
	"\n" +
	"DeleteMenu\x12\x1b.admin.v1.DeleteMenuRequest\x1a\x1c.admin.v1.DeleteMenuResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/menus/{id}B+Z)github.com/yc-alpha/admin/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_sys_menu_proto_rawDescOnce sync.Once
	file_admin_v1_sys_menu_proto_rawDescData []byte
)

func file_admin_v1_sys_menu_proto_rawDescGZIP() []byte {
	file_admin_v1_sys_menu_proto_rawDescOnce.Do(func() {
		file_admin_v1_sys_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_sys_menu_proto_rawDesc), len(file_admin_v1_sys_menu_proto_rawDesc)))
	})
	return file_admin_v1_sys_menu_proto_rawDescData
}

var file_admin_v1_sys_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_admin_v1_sys_menu_proto_goTypes = []any{
	(*Menu)(nil),               // 0: admin.v1.Menu
	(*ListMenuRequest)(nil),    // 1: admin.v1.ListMenuRequest
	(*ListMenuResponse)(nil),   // 2: admin.v1.ListMenuResponse
	(*GetMenuRequest)(nil),     // 3: admin.v1.GetMenuRequest
	(*GetMenuResponse)(nil),    // 4: admin.v1.GetMenuResponse
	(*CreateMenuRequest)(nil),  // 5: admin.v1.CreateMenuRequest
	(*CreateMenuResponse)(nil), // 6: admin.v1.CreateMenuResponse
	(*UpdateMenuRequest)(nil),  // 7: admin.v1.UpdateMenuRequest
	(*UpdateMenuResponse)(nil), // 8: admin.v1.UpdateMenuResponse
	(*DeleteMenuRequest)(nil),  // 9: admin.v1.DeleteMenuRequest
	(*DeleteMenuResponse)(nil), // 10: admin.v1.DeleteMenuResponse
}
var file_admin_v1_sys_menu_proto_depIdxs = []int32{
	0,  // 0: admin.v1.ListMenuResponse.items:type_name -> admin.v1.Menu
	0,  // 1: admin.v1.GetMenuResponse.menu:type_name -> admin.v1.Menu
	1,  // 2: admin.v1.SysMenuService.ListMenu:input_type -> admin.v1.ListMenuRequest
	3,  // 3: admin.v1.SysMenuService.GetMenu:input_type -> admin.v1.GetMenuRequest
	5,  // 4: admin.v1.SysMenuService.CreateMenu:input_type -> admin.v1.CreateMenuRequest
	7,  // 5: admin.v1.SysMenuService.UpdateMenu:input_type -> admin.v1.UpdateMenuRequest
	9,  // 6: admin.v1.SysMenuService.DeleteMenu:input_type -> admin.v1.DeleteMenuRequest
	2,  // 7: admin.v1.SysMenuService.ListMenu:output_type -> admin.v1.ListMenuResponse
	4,  // 8: admin.v1.SysMenuService.GetMenu:output_type -> admin.v1.GetMenuResponse
	6,  // 9: admin.v1.SysMenuService.CreateMenu:output_type -> admin.v1.CreateMenuResponse
	8,  // 10: admin.v1.SysMenuService.UpdateMenu:output_type -> admin.v1.UpdateMenuResponse
	10, // 11: admin.v1.SysMenuService.DeleteMenu:output_type -> admin.v1.DeleteMenuResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_admin_v1_sys_menu_proto_init() }
func file_admin_v1_sys_menu_proto_init() {
	if File_admin_v1_sys_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_sys_menu_proto_rawDesc), len(file_admin_v1_sys_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_sys_menu_proto_goTypes,
		DependencyIndexes: file_admin_v1_sys_menu_proto_depIdxs,
		MessageInfos:      file_admin_v1_sys_menu_proto_msgTypes,
	}.Build()
	File_admin_v1_sys_menu_proto = out.File
	file_admin_v1_sys_menu_proto_goTypes = nil
	file_admin_v1_sys_menu_proto_depIdxs = nil
}
