// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SysUser is the predicate function for sysuser builders.
type SysUser func(*sql.Selector)

// SysUserAccount is the predicate function for sysuseraccount builders.
type SysUserAccount func(*sql.Selector)
