// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAccount is the predicate function for useraccount builders.
type UserAccount func(*sql.Selector)

// UserDepartment is the predicate function for userdepartment builders.
type UserDepartment func(*sql.Selector)

// UserTenant is the predicate function for usertenant builders.
type UserTenant func(*sql.Selector)
